# Generated by Django 6.0 on 2026-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField()),
                ('price', models.PositiveIntegerField()),
                ('is_subscription', models.BooleanField(default=False)),
                ('duration_days', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
